name: mobile_recruitment_test
description: "Lodgify mobile recruitment app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter:
  uses-material-design: true
